export const SET_PITCHER = "SET_PITCHER";
export const REMOVE_PITCHER = "REMOVE_PITCHER";
export const RECEIVE_STREAMS = "RECEIVE_STREAMS";
export const RECEIVE_EVENTS = "RECEIVE_EVENTS";
export const SELECT_CURRENT_EVENT = "SELECT_CURRENT_EVENT";
