export const SET_PITCHER = "SET_PITCHER";
export const REMOVE_PITCHER = "REMOVE_PITCHER";
export const RECEIVE_STREAMS = "RECEIVE_STREAMS";
export const RECEIVE_EVENTS = "RECEIVE_EVENTS";
export const SET_CURRENT_EVENT = "SET_CURRENT_EVENT";
export const SET_CURRENT_STREAM = "SET_CURRENT_STREAM";
export const STOP_CURRENT_STREAM = "STOP_CURRENT_STREAM";
export const SET_CURRENT_VIEW = "SET_CURRENT_VIEW";
